//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Zavisimos
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Вход в систему.
    /// </summary>
    // *** Start programmer edit section *** (ВходВСистему CustomAttributes)

    // *** End programmer edit section *** (ВходВСистему CustomAttributes)
    [AutoAltered()]
    [Caption("Вход в систему")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ВходВСистемуE", new string[] {
            "ДатаВхода as \'Дата входа\'"})]
    [AssociatedDetailViewAttribute("ВходВСистемуE", "ТЧПользователь", "ТЧПользовательE", true, "", "Т ч пользователь", true, new string[] {
            ""})]
    [View("ВходВСистемуL", new string[] {
            "ДатаВхода as \'Дата входа\'"})]
    public class ВходВСистему : ICSSoft.STORMNET.DataObject
    {
        
        private System.DateTime fДатаВхода = System.DateTime.Now;
        
        private IIS.Zavisimos.DetailArrayOfТЧПользователь fТЧПользователь;
        
        // *** Start programmer edit section *** (ВходВСистему CustomMembers)

        // *** End programmer edit section *** (ВходВСистему CustomMembers)

        
        /// <summary>
        /// ДатаВхода.
        /// </summary>
        // *** Start programmer edit section *** (ВходВСистему.ДатаВхода CustomAttributes)

        // *** End programmer edit section *** (ВходВСистему.ДатаВхода CustomAttributes)
        public virtual System.DateTime ДатаВхода
        {
            get
            {
                // *** Start programmer edit section *** (ВходВСистему.ДатаВхода Get start)

                // *** End programmer edit section *** (ВходВСистему.ДатаВхода Get start)
                System.DateTime result = this.fДатаВхода;
                // *** Start programmer edit section *** (ВходВСистему.ДатаВхода Get end)

                // *** End programmer edit section *** (ВходВСистему.ДатаВхода Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ВходВСистему.ДатаВхода Set start)

                // *** End programmer edit section *** (ВходВСистему.ДатаВхода Set start)
                this.fДатаВхода = value;
                // *** Start programmer edit section *** (ВходВСистему.ДатаВхода Set end)

                // *** End programmer edit section *** (ВходВСистему.ДатаВхода Set end)
            }
        }
        
        /// <summary>
        /// Вход в систему.
        /// </summary>
        // *** Start programmer edit section *** (ВходВСистему.ТЧПользователь CustomAttributes)

        // *** End programmer edit section *** (ВходВСистему.ТЧПользователь CustomAttributes)
        public virtual IIS.Zavisimos.DetailArrayOfТЧПользователь ТЧПользователь
        {
            get
            {
                // *** Start programmer edit section *** (ВходВСистему.ТЧПользователь Get start)

                // *** End programmer edit section *** (ВходВСистему.ТЧПользователь Get start)
                if ((this.fТЧПользователь == null))
                {
                    this.fТЧПользователь = new IIS.Zavisimos.DetailArrayOfТЧПользователь(this);
                }
                IIS.Zavisimos.DetailArrayOfТЧПользователь result = this.fТЧПользователь;
                // *** Start programmer edit section *** (ВходВСистему.ТЧПользователь Get end)

                // *** End programmer edit section *** (ВходВСистему.ТЧПользователь Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ВходВСистему.ТЧПользователь Set start)

                // *** End programmer edit section *** (ВходВСистему.ТЧПользователь Set start)
                this.fТЧПользователь = value;
                // *** Start programmer edit section *** (ВходВСистему.ТЧПользователь Set end)

                // *** End programmer edit section *** (ВходВСистему.ТЧПользователь Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ВходВСистемуE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ВходВСистемуE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ВходВСистемуE", typeof(IIS.Zavisimos.ВходВСистему));
                }
            }
            
            /// <summary>
            /// "ВходВСистемуL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ВходВСистемуL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ВходВСистемуL", typeof(IIS.Zavisimos.ВходВСистему));
                }
            }
        }
    }
}
