//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Zavisimos
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Отделы.
    /// </summary>
    // *** Start programmer edit section *** (Отделы CustomAttributes)

    // *** End programmer edit section *** (Отделы CustomAttributes)
    public enum Отделы
    {
        
        // *** Start programmer edit section *** (Отделы.Бухгалтерия CustomAttributes)

        // *** End programmer edit section *** (Отделы.Бухгалтерия CustomAttributes)
        [Caption("Бухгалтерия")]
        Бухгалтерия,
        
        // *** Start programmer edit section *** (Отделы.Администрация CustomAttributes)

        // *** End programmer edit section *** (Отделы.Администрация CustomAttributes)
        [Caption("Администрация")]
        Администрация,
        
        // *** Start programmer edit section *** (Отделы.Проектирование CustomAttributes)

        // *** End programmer edit section *** (Отделы.Проектирование CustomAttributes)
        [Caption("Проектирование")]
        Проектирование,
        
        // *** Start programmer edit section *** (Отделы.Внедрение CustomAttributes)

        // *** End programmer edit section *** (Отделы.Внедрение CustomAttributes)
        [Caption("Внедрение")]
        Внедрение,
    }
}
