//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Zavisimos
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Права пол.
    /// </summary>
    // *** Start programmer edit section *** (ПраваПол CustomAttributes)

    // *** End programmer edit section *** (ПраваПол CustomAttributes)
    public enum ПраваПол
    {
        
        // *** Start programmer edit section *** (ПраваПол.Просмотр CustomAttributes)

        // *** End programmer edit section *** (ПраваПол.Просмотр CustomAttributes)
        [Caption("Просмотр")]
        Просмотр,
        
        // *** Start programmer edit section *** (ПраваПол.Редактирование CustomAttributes)

        // *** End programmer edit section *** (ПраваПол.Редактирование CustomAttributes)
        [Caption("Редактирование")]
        Редактирование,
        
        // *** Start programmer edit section *** (ПраваПол.Создание CustomAttributes)

        // *** End programmer edit section *** (ПраваПол.Создание CustomAttributes)
        [Caption("Создание")]
        Создание,
        
        // *** Start programmer edit section *** (ПраваПол.Отправка CustomAttributes)

        // *** End programmer edit section *** (ПраваПол.Отправка CustomAttributes)
        [Caption("Отправка")]
        Отправка,
        
        // *** Start programmer edit section *** (ПраваПол.Утверждение CustomAttributes)

        // *** End programmer edit section *** (ПраваПол.Утверждение CustomAttributes)
        [Caption("Утверждение")]
        Утверждение,
    }
}
