//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Zavisimos
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Сотрудники.
    /// </summary>
    // *** Start programmer edit section *** (Сотрудники CustomAttributes)

    // *** End programmer edit section *** (Сотрудники CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("СотрудникиE", new string[] {
            "IDСотрудника as \'I d сотрудника\'",
            "ФИОСотрудника as \'Ф и о сотрудника\'",
            "Отделы as \'Отделы\'",
            "ДатаПриема as \'Дата приема\'",
            "Зарплата as \'Зарплата\'",
            "НомерТелефона as \'Номер телефона\'",
            "Пол as \'Пол\'",
            "Должность as \'Должность\'",
            "Должность.Должность as \'Должность\'"}, Hidden=new string[] {
            "Должность.Должность"})]
    [MasterViewDefineAttribute("СотрудникиE", "Должность", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Должность")]
    [View("СотрудникиL", new string[] {
            "IDСотрудника as \'I d сотрудника\'",
            "ФИОСотрудника as \'Ф и о сотрудника\'",
            "Отделы as \'Отделы\'",
            "ДатаПриема as \'Дата приема\'",
            "Зарплата as \'Зарплата\'",
            "НомерТелефона as \'Номер телефона\'",
            "Пол as \'Пол\'",
            "Должность.Должность as \'Должность\'"})]
    public class Сотрудники : ICSSoft.STORMNET.DataObject
    {
        
        private int fIDСотрудника;
        
        private string fФИОСотрудника;
        
        private IIS.Zavisimos.Отделы fОтделы;
        
        private System.DateTime fДатаПриема;
        
        private double fЗарплата;
        
        private int fНомерТелефона;
        
        private IIS.Zavisimos.Пол fПол;
        
        private IIS.Zavisimos.Должность fДолжность;
        
        // *** Start programmer edit section *** (Сотрудники CustomMembers)

        // *** End programmer edit section *** (Сотрудники CustomMembers)

        
        /// <summary>
        /// IDСотрудника.
        /// </summary>
        // *** Start programmer edit section *** (Сотрудники.IDСотрудника CustomAttributes)

        // *** End programmer edit section *** (Сотрудники.IDСотрудника CustomAttributes)
        public virtual int IDСотрудника
        {
            get
            {
                // *** Start programmer edit section *** (Сотрудники.IDСотрудника Get start)

                // *** End programmer edit section *** (Сотрудники.IDСотрудника Get start)
                int result = this.fIDСотрудника;
                // *** Start programmer edit section *** (Сотрудники.IDСотрудника Get end)

                // *** End programmer edit section *** (Сотрудники.IDСотрудника Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Сотрудники.IDСотрудника Set start)

                // *** End programmer edit section *** (Сотрудники.IDСотрудника Set start)
                this.fIDСотрудника = value;
                // *** Start programmer edit section *** (Сотрудники.IDСотрудника Set end)

                // *** End programmer edit section *** (Сотрудники.IDСотрудника Set end)
            }
        }
        
        /// <summary>
        /// ДатаПриема.
        /// </summary>
        // *** Start programmer edit section *** (Сотрудники.ДатаПриема CustomAttributes)

        // *** End programmer edit section *** (Сотрудники.ДатаПриема CustomAttributes)
        public virtual System.DateTime ДатаПриема
        {
            get
            {
                // *** Start programmer edit section *** (Сотрудники.ДатаПриема Get start)

                // *** End programmer edit section *** (Сотрудники.ДатаПриема Get start)
                System.DateTime result = this.fДатаПриема;
                // *** Start programmer edit section *** (Сотрудники.ДатаПриема Get end)

                // *** End programmer edit section *** (Сотрудники.ДатаПриема Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Сотрудники.ДатаПриема Set start)

                // *** End programmer edit section *** (Сотрудники.ДатаПриема Set start)
                this.fДатаПриема = value;
                // *** Start programmer edit section *** (Сотрудники.ДатаПриема Set end)

                // *** End programmer edit section *** (Сотрудники.ДатаПриема Set end)
            }
        }
        
        /// <summary>
        /// Зарплата.
        /// </summary>
        // *** Start programmer edit section *** (Сотрудники.Зарплата CustomAttributes)

        // *** End programmer edit section *** (Сотрудники.Зарплата CustomAttributes)
        public virtual double Зарплата
        {
            get
            {
                // *** Start programmer edit section *** (Сотрудники.Зарплата Get start)

                // *** End programmer edit section *** (Сотрудники.Зарплата Get start)
                double result = this.fЗарплата;
                // *** Start programmer edit section *** (Сотрудники.Зарплата Get end)

                // *** End programmer edit section *** (Сотрудники.Зарплата Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Сотрудники.Зарплата Set start)

                // *** End programmer edit section *** (Сотрудники.Зарплата Set start)
                this.fЗарплата = value;
                // *** Start programmer edit section *** (Сотрудники.Зарплата Set end)

                // *** End programmer edit section *** (Сотрудники.Зарплата Set end)
            }
        }
        
        /// <summary>
        /// НомерТелефона.
        /// </summary>
        // *** Start programmer edit section *** (Сотрудники.НомерТелефона CustomAttributes)

        // *** End programmer edit section *** (Сотрудники.НомерТелефона CustomAttributes)
        public virtual int НомерТелефона
        {
            get
            {
                // *** Start programmer edit section *** (Сотрудники.НомерТелефона Get start)

                // *** End programmer edit section *** (Сотрудники.НомерТелефона Get start)
                int result = this.fНомерТелефона;
                // *** Start programmer edit section *** (Сотрудники.НомерТелефона Get end)

                // *** End programmer edit section *** (Сотрудники.НомерТелефона Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Сотрудники.НомерТелефона Set start)

                // *** End programmer edit section *** (Сотрудники.НомерТелефона Set start)
                this.fНомерТелефона = value;
                // *** Start programmer edit section *** (Сотрудники.НомерТелефона Set end)

                // *** End programmer edit section *** (Сотрудники.НомерТелефона Set end)
            }
        }
        
        /// <summary>
        /// Отделы.
        /// </summary>
        // *** Start programmer edit section *** (Сотрудники.Отделы CustomAttributes)

        // *** End programmer edit section *** (Сотрудники.Отделы CustomAttributes)
        public virtual IIS.Zavisimos.Отделы Отделы
        {
            get
            {
                // *** Start programmer edit section *** (Сотрудники.Отделы Get start)

                // *** End programmer edit section *** (Сотрудники.Отделы Get start)
                IIS.Zavisimos.Отделы result = this.fОтделы;
                // *** Start programmer edit section *** (Сотрудники.Отделы Get end)

                // *** End programmer edit section *** (Сотрудники.Отделы Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Сотрудники.Отделы Set start)

                // *** End programmer edit section *** (Сотрудники.Отделы Set start)
                this.fОтделы = value;
                // *** Start programmer edit section *** (Сотрудники.Отделы Set end)

                // *** End programmer edit section *** (Сотрудники.Отделы Set end)
            }
        }
        
        /// <summary>
        /// Пол.
        /// </summary>
        // *** Start programmer edit section *** (Сотрудники.Пол CustomAttributes)

        // *** End programmer edit section *** (Сотрудники.Пол CustomAttributes)
        public virtual IIS.Zavisimos.Пол Пол
        {
            get
            {
                // *** Start programmer edit section *** (Сотрудники.Пол Get start)

                // *** End programmer edit section *** (Сотрудники.Пол Get start)
                IIS.Zavisimos.Пол result = this.fПол;
                // *** Start programmer edit section *** (Сотрудники.Пол Get end)

                // *** End programmer edit section *** (Сотрудники.Пол Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Сотрудники.Пол Set start)

                // *** End programmer edit section *** (Сотрудники.Пол Set start)
                this.fПол = value;
                // *** Start programmer edit section *** (Сотрудники.Пол Set end)

                // *** End programmer edit section *** (Сотрудники.Пол Set end)
            }
        }
        
        /// <summary>
        /// ФИОСотрудника.
        /// </summary>
        // *** Start programmer edit section *** (Сотрудники.ФИОСотрудника CustomAttributes)

        // *** End programmer edit section *** (Сотрудники.ФИОСотрудника CustomAttributes)
        [StrLen(255)]
        public virtual string ФИОСотрудника
        {
            get
            {
                // *** Start programmer edit section *** (Сотрудники.ФИОСотрудника Get start)

                // *** End programmer edit section *** (Сотрудники.ФИОСотрудника Get start)
                string result = this.fФИОСотрудника;
                // *** Start programmer edit section *** (Сотрудники.ФИОСотрудника Get end)

                // *** End programmer edit section *** (Сотрудники.ФИОСотрудника Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Сотрудники.ФИОСотрудника Set start)

                // *** End programmer edit section *** (Сотрудники.ФИОСотрудника Set start)
                this.fФИОСотрудника = value;
                // *** Start programmer edit section *** (Сотрудники.ФИОСотрудника Set end)

                // *** End programmer edit section *** (Сотрудники.ФИОСотрудника Set end)
            }
        }
        
        /// <summary>
        /// Сотрудники.
        /// </summary>
        // *** Start programmer edit section *** (Сотрудники.Должность CustomAttributes)

        // *** End programmer edit section *** (Сотрудники.Должность CustomAttributes)
        [PropertyStorage(new string[] {
                "Должность"})]
        [NotNull()]
        public virtual IIS.Zavisimos.Должность Должность
        {
            get
            {
                // *** Start programmer edit section *** (Сотрудники.Должность Get start)

                // *** End programmer edit section *** (Сотрудники.Должность Get start)
                IIS.Zavisimos.Должность result = this.fДолжность;
                // *** Start programmer edit section *** (Сотрудники.Должность Get end)

                // *** End programmer edit section *** (Сотрудники.Должность Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Сотрудники.Должность Set start)

                // *** End programmer edit section *** (Сотрудники.Должность Set start)
                this.fДолжность = value;
                // *** Start programmer edit section *** (Сотрудники.Должность Set end)

                // *** End programmer edit section *** (Сотрудники.Должность Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "СотрудникиE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View СотрудникиE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("СотрудникиE", typeof(IIS.Zavisimos.Сотрудники));
                }
            }
            
            /// <summary>
            /// "СотрудникиL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View СотрудникиL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("СотрудникиL", typeof(IIS.Zavisimos.Сотрудники));
                }
            }
        }
    }
}
