//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Zavisimos
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Утверждение.
    /// </summary>
    // *** Start programmer edit section *** (Утверждение CustomAttributes)

    // *** End programmer edit section *** (Утверждение CustomAttributes)
    public enum Утверждение
    {
        
        // *** Start programmer edit section *** (Утверждение.Утвержден CustomAttributes)

        // *** End programmer edit section *** (Утверждение.Утвержден CustomAttributes)
        [Caption("Утвержден")]
        Утвержден,
        
        // *** Start programmer edit section *** (Утверждение.НеУтвержден CustomAttributes)

        // *** End programmer edit section *** (Утверждение.НеУтвержден CustomAttributes)
        [Caption("НеУтвержден")]
        НеУтвержден,
    }
}
